### ISSUE TITLE
invalid option: window-size

### ISSUE THREAD

**Issue by ctlong** [luan/tmuxfiles#11]
On Ubuntu 18.04, I ran:
```
git clone https://github.com/luan/tmuxfiles.git "${HOME}/.config/tmux"
"${HOME}/.config/tmux/install"
```

The install script ran successfully, but now whenever I start a new tmux session I get the following error message on startup: `.tmux.conf:20: invalid option: window-size`

**Comment by ctlong** [comment]
Might be related to: https://github.com/tmux/tmux/issues/1688

**Comment by luan** [comment]
What version of tmux are you running? Given it's Ubuntu 18.04 I'd imagine it's not recent enough.

**Comment by ctlong** [comment]
You're right, it's only tmux v2.6. I commented out that [line](https://github.com/luan/tmuxfiles/blob/master/tmux.conf#L20), as well as one [other line](https://github.com/luan/tmuxfiles/blob/master/tmux.conf#L45) that was throwing an `invalid command: C-M-\\` error, and now everything seems to be working ?

**Comment by luan** [comment]
Yeah, that's quite old. This config doesn't try to be backwards compatible in any way. And apparently neither does tmux...
I'd recommend you try to get a more recent version installed via some PPA or by compiling tmux yourself if you want to use latest.

**Comment by ctlong** [comment]
Okay, thanks! Upgraded to Ubuntu 20.04 LTS and tmux 3.0a, and everything seems to be working great.
