### ISSUE TITLE
Want some extra stuff in the README?

### ISSUE THREAD

**Issue by totherme** [luan/tmuxfiles#9]
Some teammates needed a cheetsheet for how to use tmux (with these configs) the other day, so I wrote [this](https://gist.github.com/totherme/a3e30612c19564127758ff7c2fc89e5b).

Would you like it PRed into your README or similar? Or should it stay as a gist where it is?

**Comment by luan** [comment]
I'm sorry I missed this last year. I'd love the PR if you still have the cycles to do it :) Otherwise, I might look at your document later to pull some stuff in myself.

**Comment by totherme** [comment]
PR Opened :)
